# Generated by Django 6.0.3 on 2026-04-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='jobs.application'),
        ),
    ]
