# Generated by Django 6.0.3 on 2026-04-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_payment_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_fee',
            field=models.IntegerField(default=500, help_text='Application fee in INR for this specific job'),
        ),
    ]
