# Generated by Django 6.0.3 on 2026-04-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_application_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
