# Generated by Django 6.0.3 on 2026-04-12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def _with_suffix(value, suffix, max_len=255):
    safe_base = value or 'unknown'
    candidate = f'{safe_base}{suffix}'
    if len(candidate) > max_len:
        trim = max_len - len(suffix)
        candidate = f'{safe_base[:max(1, trim)]}{suffix}'
    return candidate


def dedupe_payment_identifiers(apps, schema_editor):
    Payment = apps.get_model('jobs', 'Payment')

    duplicate_orders = (
        Payment.objects.values('razorpay_order_id')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for row in duplicate_orders.iterator():
        order_id = row['razorpay_order_id']
        dupes = Payment.objects.filter(razorpay_order_id=order_id).order_by('id')
        for payment in dupes[1:]:
            payment.razorpay_order_id = _with_suffix(order_id, f'__dup_{payment.id}')
            payment.save(update_fields=['razorpay_order_id'])

    duplicate_payments = (
        Payment.objects.exclude(razorpay_payment_id__isnull=True)
        .exclude(razorpay_payment_id='')
        .values('razorpay_payment_id')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for row in duplicate_payments.iterator():
        payment_id = row['razorpay_payment_id']
        dupes = Payment.objects.filter(razorpay_payment_id=payment_id).order_by('id')
        for payment in dupes[1:]:
            payment.razorpay_payment_id = _with_suffix(payment_id, f'__dup_{payment.id}')
            payment.save(update_fields=['razorpay_payment_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_application_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_payment_identifiers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'email'), name='uniq_application_per_job_email'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paise',
            field=models.PositiveIntegerField(default=0, help_text='Amount in paise'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in INR'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Success', 'Success'), ('Failed', 'Failed'), ('Duplicate', 'Duplicate'), ('Cancelled', 'Cancelled')], db_index=True, default='Initiated', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['email', 'created_at'], name='jobs_paymen_email_c69f34_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='jobs_paymen_status_5e77f8_idx'),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('Processed', 'Processed'), ('Failed', 'Failed')], default='Processed', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
