# Generated by Django 6.0.3 on 2026-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_payment_security_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Success', 'Success'), ('Failed', 'Failed'), ('Duplicate', 'Duplicate'), ('Cancelled', 'Cancelled'), ('NeedsReview', 'NeedsReview')], db_index=True, default='Initiated', max_length=50),
        ),
    ]
