"""
Django settings for job_portal project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() in ('1', 'true', 'yes')

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-insecure-change-me'
    else:
        raise ValueError('DJANGO_SECRET_KEY is required when DEBUG is False')

if DEBUG:
    ALLOWED_HOSTS = []
else:
    ALLOWED_HOSTS = [
        host.strip()
        for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
        if host.strip()
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'jobs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'job_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'job_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Directory where Django will look for additional static files
STATICFILES_DIRS = [BASE_DIR / 'static']

# Directory where collectstatic will collect static files to
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User-uploaded content like resumes or profile pictures)
MEDIA_URL = 'media/'
# The absolute path to the directory where media files will be stored
MEDIA_ROOT = BASE_DIR / 'media'

# AWS S3 Settings (for media/resumes)
USE_S3 = os.environ.get('USE_S3', 'TRUE').strip().upper() == 'TRUE'
if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    
    # Store media files on S3
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    # DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'  # Deprecated in Django 4.2+
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    
    # Optional: If you also want to host static files (CSS/JS) on S3, uncomment below
    # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

# Razorpay Integration Settings
# Replace these with your actual test/live keys from Razorpay Dashboard
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')
PAYMENTS_REQUIRE_AUTHENTICATION = os.environ.get('PAYMENTS_REQUIRE_AUTHENTICATION', 'False').strip().lower() in ('1', 'true', 'yes')
TRUSTED_PROXY = os.environ.get('TRUSTED_PROXY', 'False').strip().lower() in ('1', 'true', 'yes')

if not DEBUG:
    if not RAZORPAY_KEY_ID or not RAZORPAY_KEY_SECRET or not RAZORPAY_WEBHOOK_SECRET:
        raise ValueError('Razorpay keys and webhook secret are required when DEBUG is False')

# Email Settings (Using console backend for testing, switch to smtp when deploying)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Application configuration (moved from config.py)
COMPANY_NAME = "AVORRE"
COMPANY_PHONE = "+91 6006010775"
COMPANY_PHONE_SHORT = "6006010775"
COMPANY_ADDRESS = "Shivalkpuram, Sec 8, Roop Nagar, Jammu"
COMPANY_WEBSITE = ""
CURRENT_YEAR = 2026

# Payment Configuration
APPLICATION_FEE_INR = 100  # Amount in INR for job application
CURRENCY = "INR"

# Color Scheme (Dark + Gold Theme)
COLOR_DARK_PRIMARY = "#121415"
COLOR_DARK_SECONDARY = "#1b1d1f"
COLOR_DARK_TERTIARY = "#0d0f10"
COLOR_ACCENT_GOLD = "#c5a85f"
COLOR_TEXT_LIGHT = "#f5f5f5"
COLOR_GOLD_LIGHT = "#d4b872"
COLOR_GOLD_DARK = "#b09144"
COLOR_GOLD_DARKER = "#8c7336"

# Job Application Messages
MESSAGE_PAYMENT_SUCCESS = "Application Successful!"
MESSAGE_PAYMENT_SUCCESS_DESC = "Thank you for applying. We have received your details and resume. Our recruitment team will review your application and be in touch with you shortly."
MESSAGE_PAYMENT_FAILED = "Payment Verification Failed. Please try again."
MESSAGE_NO_JOBS = "No job openings available at the moment."

# Service Descriptions
SERVICES = [
    {
        "title": "Security Services",
        "description": "Guards, Supervisors, Bouncers",
        "icon": "fa-shield-virus"
    },
    {
        "title": "Manpower Supply",
        "description": "Labour, Helpers, Drivers",
        "icon": "fa-helmet-safety"
    },
    {
        "title": "Facility Management",
        "description": "Housekeeping, Maintenance",
        "icon": "fa-building-user"
    }
]

# Hero Section Text
HERO_TITLE = "Professional Security<br>& Manpower Solutions"
HERO_SUBTITLE = "Trusted Protection and Reliable Workforce for All Industries"
HERO_BUTTON_PRIMARY = "Apply for Job"
HERO_BUTTON_SECONDARY = "Get Quote"

# Home Page Sections
SECTION_SERVICES = "Services"
SECTION_JOBS = "Current Job Openings"
SECTION_JOBS_ID = "jobs"
SECTION_CONTACT = "Contact Us"

# URL Paths (for navigation)
URL_HOME = "/"
URL_JOBS = "/jobs/"
URL_APPLY = "/apply/"

# Basic production security hardening
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
